Chatspace front
teru0225/chat-space pull request #2
Opened 2019-01-09 08:11 UTC by teru0225

I coded for the view of chat-space front(message screen)

2019-01-09 08:44 UTC, 40213151 commented on app/views/messages/index.html.haml
> +      %a.leftHeader__settingIcon{:href => "#"} <i class="fa fa-cog" aria-hidden="true"></i>
こちらのアイコンですが、Railsのヘルパーメソッドを使用して表示しましょう！

2019-01-09 08:44 UTC, 40213151 commented on app/views/messages/index.html.haml
> +      %a.leftHeader__editIcon{:href => "#"} <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
こちらのアイコンですが、Railsのヘルパーメソッドを使用して表示しましょう！

2019-01-09 08:49 UTC, 40213151 commented
プルリクエストを出す際は、WHAT.WHYなど、プルリクの詳細が第三者からわかる様にしましょう！
(例: その機能を実装するとどの様なメリットを産むのか)
Viewの実装の際は、Gyazoを使用しスクリーンショットを載せていただくとよりわかりやすいです

2019-01-11 08:52 UTC, teru0225 commented
> プルリクエストを出す際は、WHAT.WHYなど、プルリクの詳細が第三者からわかる様にしましょう！
> (例: その機能を実装するとどの様なメリットを産むのか)
> Viewの実装の際は、Gyazoを使用しスクリーンショットを載せていただくとよりわかりやすいです

レビューありがとうございます。
スクリーンショットの件、かしこまりました。

2019-01-11 08:58 UTC, yutakatahira commented
以前コメントしていただいた分は、修正していますでしょうか？

2019-01-11 08:59 UTC, yutakatahira commented
また、cacheがgithub上に上がってきているので、.gitignoreに記述して上がらないようにしましょう。

2019-01-12 04:49 UTC, teru0225 commented
> 以前コメントしていただいた分は、修正していますでしょうか？

Railsのヘルパーメソッドを使うようにとのご指摘は、すでに修正済みです。

2019-01-12 04:52 UTC, teru0225 commented
> また、cacheがgithub上に上がってきているので、.gitignoreに記述して上がらないようにしましょう。

ターミナルにて、git rm -r --cachedコマンドを実行して、cacheが上がらないようにしました。

2019-01-12 05:24 UTC, ta910 commented on app/views/messages/index.html.haml
> +      %a.leftHeader__settingIcon{:href => "#"} <i class="fa fa-cog" aria-hidden="true"></i>
こちらヘルパーメソッド(link_to)を使う修正の反映をお願いいたします

2019-01-12 05:25 UTC, ta910 commented
WHY,WHAT,スクリーンショットをPRに記述しましょう！
このPRからしっかり変えていきましょう

2019-01-12 05:27 UTC, ta910 commented
キャッシュがあるとファイル数が多すぎてレビューが難しいため、キャッシュファイルがFile Changedに反映されないようにお願いしたいです。

キャッシュファイルを全て削除してからもう一度pushして、そのあとにgitignoreに追加する方法が良いかと思います」

2019-01-16 08:36 UTC, teru0225 commented
> キャッシュがあるとファイル数が多すぎてレビューが難しいため、キャッシュファイルがFile Changedに反映されないようにお願いしたいです。
> 
> キャッシュファイルを全て削除してからもう一度pushして、そのあとにgitignoreに追加する方法が良いかと思います」

指摘していただいた２点を改善しました。
よろしくお願いいたします。

2019-01-16 08:56 UTC, 40213151 commented on app/assets/stylesheets/_style.scss
> +.rightBody {
こちらの要素ですが、メッセージが多く投稿された分はスクロールで表示できる様にしましょう！
もし方法が分からなければTech::connectでメンターにお聞きください！

2019-01-16 08:57 UTC, 40213151 commented
index.htmlにてヘルパーメソッド(link_to)を使用する変更は、反映されていますでしょうか？
今一度ご確認お願いします！

2019-01-19 07:41 UTC, teru0225 commented
> index.htmlにてヘルパーメソッド(link_to)を使用する変更は、反映されていますでしょうか？
> 今一度ご確認お願いします！

指摘いただいた点、修正いたしました。
もう一度、ご確認お願いいたします。
ちなみに、index.html.hamlは以下のようになっています。
<img width="735" alt="index" src="https://user-images.githubusercontent.com/45619905/51423831-0246f980-1c09-11e9-8c2a-a1b8d20d414b.png">

2019-01-19 07:53 UTC, ghost requested changes

2019-01-19 07:53 UTC, hiroki5123 commented on app/views/messages/_main.html.haml
> +        %a.rightHeader_group_edit{:href => "#"} Edit
ここlink_toで書きましょう

2019-01-19 07:53 UTC, hiroki5123 commented on tmp/pids/server.pid
> +1468
このファイルもgitignoreしましょう

2019-01-19 08:04 UTC, teru0225 commented on app/views/messages/_main.html.haml
> +        %a.rightHeader_group_edit{:href => "#"} Edit
ご指摘いただいた２点、修正しました。
再度、ご確認よろしくお願いいたします。

2019-01-19 08:09 UTC, hiroki5123 commented on log/development.log
このファイルもgitignoreしましょう

tmp以下は全てgitignoreしてしまって大丈夫です

2019-01-19 08:16 UTC, teru0225 commented on log/development.log
かしこまりました。
gitignoreは以下のようななっております。
また、development.logファイルとtmp/cache/assets以下のファイルは削除しました。
<img width="461" alt="index2" src="https://user-images.githubusercontent.com/45619905/51424189-e5f98b80-1c0d-11e9-83c8-d51da5cd0bb7.png">

2019-01-19 08:22 UTC, yuki-uchida requested changes
BEMのクラス設計だけもう少し修正できそうですね！

2019-01-19 08:22 UTC, yuki-uchida commented on app/assets/stylesheets/_main.scss
> +.rightBody3 {
rightBody1,2,3という命名は、何か他にわかりやすいものを考えて見て欲しいです。
right__body--headerなど、BEMの形に沿って書いてあるとより良いです。全体的に、クラス名は修正できそうですね。

2019-01-19 08:22 UTC, yuki-uchida commented on app/assets/stylesheets/_main.scss
> +.rightBody3 {
https://qiita.com/Takuan_Oishii/items/0f0d2c5dc33a9b2d9cb1

2019-01-19 08:22 UTC, yuki-uchida commented on app/assets/stylesheets/_main.scss
> +.rightFooter {
こちらも、B(Block) E(Element) M(Modifer)に沿って言えば、
right__body--footerなどに出来ると思います

2019-01-19 09:48 UTC, teru0225 commented on app/assets/stylesheets/_main.scss
> +.rightFooter {
ご指摘いただきありがとうございます。
送っていただいた記事を見て、BEMでの設計をし直しました。
ご確認、よろしくお願いいたします。

2019-01-19 09:50 UTC, ghost approved these changes
LGTMです！

2019-01-20 05:42 UTC, merged